# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-06-27 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200627_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hot',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
